/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme\nocturne.ts
 * Command: astryx theme build theme\nocturne.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const taskifyNocturneTheme: DefinedTheme;
